### ISSUE TITLE
Passing a zip code string that starts with an 0 returns an error

### ISSUE THREAD

**Issue by tylerpearson** [taxjar/taxjar-ruby#18]
Hey guys, we've hit an issue where passing a zip code as a string that begins with a 0 is causing a `Taxjar::Error::NotFound: Resource can not be found` error. 

For example: `@taxjar.rates_for_location('00150')`

In the last hour, we've also had issues with `"01915"`, `"06108"`, `"06902"`, `"02125"`, `"07601"`, and some others, all starting with 0. 

Unless I'm missing something this actually doesn't seem to be an issue with the Ruby client because this is failing with a curl request too. I didn't see a spot in the docs to send a message, so figured I'd try through here first.

**Comment by tonkapark** [comment]
We are working on a fix.

**Comment by tylerpearson** [comment]
Awesome! Thanks.

**Comment by tonkapark** [comment]
The API responses for the leading 0 zip codes has been resolved.

**Comment by tylerpearson** [comment]
Thanks! You guys are quick :rocket:
