### ISSUE TITLE
ArgumentError: invalid value for Integer() when accessing ID

### ISSUE THREAD

**Issue by mfichman** [taxjar/taxjar-ruby#22]
If I set a line item's ID to an arbitrary string when calling `tax_for_order`, then accessing the returned `tax.breakdown.line_items` array throws an ArgumentError.

Here's an example that reproduces the problem:

```
tax = client.tax_for_order(
  :to_city=>"San Jose", 
  :to_country=>"US", 
  :to_state=>"CA", :to_zip=>"95131", 
  :from_city=>"San Jose", 
  :from_country=>"US", :from_state=>"CA", 
  :from_zip=>"95131", 
  :shipping=>"7.25", 
  :line_items=>[{
    :id=>"product_line_item_0", 
    :quantity=>1, 
    :discount=>"0.00", 
    :unit_price=>"99.99"
  }]
)

# Throws "ArgumentError: invalid value for Integer() when accessing ID"
puts tax.breakdown.line_items
```

This is problematic, b/c the `id` field of a `line_item` is a string (not necessarily an integer), per the API documentation [here.](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order)

EDIT: I'm using `taxjar-ruby` v1.5.0.

**Comment by fastdivision** [comment]
@mfichman Thanks for catching this, I'll get it updated today.

**Comment by mfichman** [comment]
@fastdivision Sweet, thanks for the quick response!
