### ISSUE TITLE
Undefined method `combined_tax_rate` for Taxjar::BreakdownLineItem

### ISSUE THREAD

**Issue by chrisyuska** [taxjar/taxjar-ruby#24]
Version: 1.4.0

When calculating sales tax for an order per https://developers.taxjar.com/api/reference/?ruby#post-calculate-sales-tax-for-an-order, it says the response should include `combined_tax_rate` and `taxable_amount` properties for each provided line item.  However, both methods appear to be undefined.

Using the deprecated `line_item[:combined_tax_rate]` or `line_item[:taxable_amount]` both return nil (though without error).  However, converting the line item to a hash first will return the correct values for these attributes like so: `line_item.to_h[:combined_tax_rate]`.

This value can be manually calculated from other values, but the behavior is inconsistent with the API reference.

**Comment by fastdivision** [comment]
Hi @chrisyuska, we added these properties to breakdown line items in v1.5.0: https://github.com/taxjar/taxjar-ruby/blob/v1.5.0/lib/taxjar/breakdown_line_item.rb

Can you upgrade to the latest version (if possible) and let me know if you're still encountering these issues? Thank you!

**Comment by chrisyuska** [comment]
Doh!  I didn't realize we were out of date.  v1.5.0 and v1.6.0 work just fine.  Thanks for the quick response.
