### ISSUE TITLE
Dependancy on  http 1.0.4

### ISSUE THREAD

**Issue by boyankirov** [taxjar/taxjar-ruby#27]
Hi,

We are using the component and we are wondering what caused the revert in the HTTP gem versions.

Namely https://github.com/taxjar/taxjar-ruby/commit/2e784c845a744bcf1251f1b09ee301be604134e6 and then https://github.com/taxjar/taxjar-ruby/commit/bcfc4ad42a280b619c825fbe55bd72e6b3f8ad43 after a failed CI build.

The problem is that we will have to downgrade because of this dependency.

**Comment by fastdivision** [comment]
Hi @boyankirov,

That was an interim commit in a pull request while attempting to upgrade the HTTP gem to `2.2.2`. I should have squashed it. We officially went from `0.9.4` to `1.0.4` in the latest version of our gem. `0.9.4` was becoming fairly outdated, so we decided to upgrade it.

The latest version of our gem only includes that change, so you should be fine downgrading our gem without losing any functionality.

**Comment by boyankirov** [comment]
Hi @fastdivision ,

Thanks for the fast reply! We were wandering why the upgrade to 2.2.2 failed and if you have any plans for fixing the reason for that . 
We were using http 2.2.2 in our application and because of the TaxJar gem we had to downgrade to http 1.0.4

**Comment by fastdivision** [comment]
The upgrade to `2.2.2` broke our Ruby 1.9.3 build in Travis, `2.2.2` requires Ruby >= 2.0. We're still supporting Ruby 1.9.3+ at this time. I'd be open to requiring Ruby 2.0+ in a major version update (v2.0.0 for our gem) and then backfilling future functionality in v1.x for people using older versions of Ruby. I'll discuss with our team.

**Comment by boyankirov** [comment]
Thanks for the details !

Hopefully you will have the update ready soon. Until then we will have to go with the current gem, test with http 1.0.4 and keep our fingers crossed :)

**Comment by zhubert** [comment]
@fastdivision Any updates on this?

**Comment by fastdivision** [comment]
@zhubert I'll try to get it updated this week. Thanks for the reminder!
