### ISSUE TITLE
New version of `http`. Should bump gemspec.

### ISSUE THREAD

**Issue by kulte** [taxjar/taxjar-ruby#33]

**Comment by fastdivision** [comment]
Latest version of the HTTP gem [requires Ruby 2.3+](https://github.com/httprb/http/blob/master/http.gemspec). We're still interested in supporting Ruby 2.0+ for now, but I'll keep this issue open for additional feedback. Thanks!

**Comment by andrewjaanuu** [comment]
+1

**Comment by fastdivision** [comment]
Thanks for the suggestion, @zanker! I'll relax the version requirement and push an update shortly.

**Comment by zanker** [comment]
(Also I double checked and it looks like tests pass against 3.x and 4.x)
