### ISSUE TITLE
Calculate Sales Tax for a Saas based product without shipping

### ISSUE THREAD

**Issue by zeeshangulzar** [taxjar/taxjar-ruby#39]
We are providing software as services using monthly/yearly subscription. Payment is done using stripe. We have monthly/yearly payments and few one time charge payments using stripe charge API. As per taxjar blog, we need to calculate it by taxjar api.
https://developers.taxjar.com/blog/handling-sales-tax-with-stripe/

We decided to calculate sales tax using rate api. But it doesn't support product_tax_code so i can mention my product_type as saas(product_tax_code). So it even calculate tax for California which is non-taxable state for Saas

https://blog.taxjar.com/saas-sales-tax/

**SAAS Category **

    `{
      "name": "Software as a Service",
      "product_tax_code": "30070",
      "description": "Pre-written software, delivered electronically, but access remotely."
    }`
    
**Rate API Code**

```
client = Taxjar::Client.new(api_key: api_key)
 tax = client.rates_for_location(address.zip, { city: address.city, state: address.state, country: address.country_code })

```

Then i tried to use `tax_for_order` function, but as it is a subscription, there is no shipping and without shipping it give sales tax 0.0 results to every state.

```
 client.tax_for_order({
    :to_country => 'US',
    :to_zip => '99217',
    :to_city => 'Spokane',
    :to_state => 'WA',
    :from_country => 'US',
    :from_zip => '97005',
    :from_city => 'Beaverton',
    :from_state => 'OR',
    :amount => 15,
    :shipping => 0,
    :nexus_addresses => [{:address_id => 1,
                          :country => 'US',
                          :zip => '93101',
                          :state => 'OR',
                          :city => 'Beaverton''}],
    :line_items => [{:quantity => 1,
                     :unit_price => 15,
                     :product_tax_code => 30070}]
}) 
```

So goal is to calculate sales tax for a saas based product without shipping. Please if you can guide me in right direction.

**Comment by fastdivision** [comment]
Hi @zeeshangulzar, [Oregon](https://www.taxjar.com/states/oregon-sales-tax-online/) does not have a sales tax. You only need to collect sales tax in states where you have nexus. In the example you provided, you're receiving $0 in sales tax because you don't have nexus in Washington. The `shipping` param does not affect the total calculation, but it will be taxed in states where you have nexus and freight is taxable. Hope this helps!
