### ISSUE TITLE
Issue accessing line_items in breakdown

### ISSUE THREAD

**Issue by deremer** [taxjar/taxjar-ruby#4]
```
resp = @taxjar.tax_for_order(@order_req)
resp.breakdown.line_items
```
Results in: **RuntimeError: can't modify frozen Taxjar::Breakdown** from line 13 of breakdown.rb

**Comment by deremer** [comment]
just adding :line_items to the attr_reader and commenting out the line_items method seems to give us the access to the line_items we are looking for...but then we have to access the attributes by their symbols instead of as methods (e.g., a.breakdown.line_items[0][:id])

**Comment by fastdivision** [comment]
@deremer Should be fixed now w/ additional spec. Thank you for reporting this issue! :smile:

**Comment by deremer** [comment]
No problem. Thanks for taking a look and fixing quickly. As mentioned in my follow-up comment, the code is also like this in order.rb and refund.rb, but I haven’t tested to see if the same problem exists in those places.



-- 
David DeRemer

On October 9, 2015 at 2:15:14 PM, Jake Johnson (notifications@github.com) wrote:

@deremer Should be fixed now w/ additional spec. Thank you for reporting this issue!
