### ISSUE TITLE
Support for Ruby 1.9.3

### ISSUE THREAD

**Issue by mrbiggred** [taxjar/taxjar-ruby#40]
I noticed in issue #27 you talked about continuing support for Ruby 1.9.3.  Did you decide to continue to support Ruby 1.9.3?  I'm assuming not but thought I would check.  Thank you.

**Comment by fastdivision** [comment]
Hi @mrbiggred, we decided to upgrade the HTTP gem which required Ruby 2.0+. If you'd like to use Ruby 1.9.3, you could fork the client and lower the HTTP gem version in the gemspec.
