### ISSUE TITLE
How does the the dependency on model_attributes work?

### ISSUE THREAD

**Issue by fay-stripe** [taxjar/taxjar-ruby#42]
Hi! I'm trying to use the Taxjar ruby gem, and have a question about its dependencies. The gemspec indicates that it uses `model_attributes, '~> 3.2'` here: https://github.com/taxjar/taxjar-ruby/blob/master/taxjar-ruby.gemspec#L26
But the README (https://github.com/taxjar/taxjar-ruby#gem-dependencies) says it depends on a forked version. And the forked version also has a different name: https://github.com/taxjar/model_attribute/blob/master/taxjar-model_attribute.gemspec#L7 

It seems to me like Taxjar doesn't depend on the forked version, right?

Thanks!

**Comment by prsimp** [comment]
Hi @fay-stripe! You're correct that this gem no longer uses the forked version of the `model_attribute` gem. You can see the change back to the original gem in https://github.com/taxjar/taxjar-ruby/commit/62408b628f6edc02d932a13fd7435e22eba02c83.

We were able to move back to the original gem after float support was added (based on the forked version) in https://github.com/yammer/model_attribute/pull/10.

Thanks for pointing out the error in the README, we'll get it fixed ASAP!

**Comment by fay-stripe** [comment]
Perfect, thanks!!
