### ISSUE TITLE
HTTP::Error: Unknown MIME type: text/html in rare cases

### ISSUE THREAD

**Issue by yjukaku** [taxjar/taxjar-ruby#50]
Hello! 👋  It seems that calling the Taxjar API sometimes returns an HTML (not JSON) response. In that case, this library fails with `HTTP::Error: Unknown MIME type: text/html`, due to the call to `Http::Request#parse`.

1. Do you have any idea when/why the Taxjar API would return HTML?
2. Can we raise a more helpful error in these cases?

Thanks!

Here's a sample backtrace:
```ruby
HTTP::Error: Unknown MIME type: text/html 
File /app/vendor/bundle/ruby/2.6.0/gems/http-4.1.1/lib/http/mime_type.rb line 38 in []
File /app/vendor/bundle/ruby/2.6.0/gems/http-4.1.1/lib/http/response.rb line 158 in parse
File /app/vendor/bundle/ruby/2.6.0/gems/taxjar-ruby-2.6.0/lib/taxjar/api/request.rb line 31 in perform
File /app/vendor/bundle/ruby/2.6.0/gems/taxjar-ruby-2.6.0/lib/taxjar/api/utils.rb line 7 in perform_request
File /app/vendor/bundle/ruby/2.6.0/gems/taxjar-ruby-2.6.0/lib/taxjar/api/utils.rb line 39 in perform_request_with_object
File /app/vendor/bundle/ruby/2.6.0/gems/taxjar-ruby-2.6.0/lib/taxjar/api/utils.rb line 11 in perform_get_with_object
File /app/vendor/bundle/ruby/2.6.0/gems/taxjar-ruby-2.6.0/lib/taxjar/api/api.rb line 12 in rates_for_location
```

**Comment by ScottRudiger** [comment]
@yjukaku Thanks for the issue and corresponding PR! We'll get the PR reviewed and get a handle on this bug shortly. 👍

**Comment by yjukaku** [comment]
👏 Thanks @ScottRudiger ! Looking forward to a fix here as we're getting some error reports with our integration. 😅
