### ISSUE TITLE
Stripe Subscription Integration Questions

### ISSUE THREAD

**Issue by antwonlee** [taxjar/taxjar-ruby#55]
I am looking at Stripe-Taxjar [documentation](https://stripe.com/docs/orders/taxjar), but it seems like it is deprecated.

I have a rails app that charges Stripe subscriptions, what would be the best way to implement this? 

I linked the Stripe in the Taxjar dashboard, but it didn't import any of the transactions.  It indicates it only works with Relay orders.

Is SmartCalcs API [transaction](https://developers.taxjar.com/api/reference/#get-list-order-transactions) going to create transactions in Taxjar [dashboard](https://app.taxjar.com/transactions)?

**Comment by ScottRudiger** [comment]
At a high level, you can add a tax percentage to recurring subscriptions or create your own tax rates based on [v2/taxes](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order) using Stripe's API. To push subscription invoices into TaxJar as orders, you would use [Stripe's webhooks](https://stripe.com/docs/billing/webhooks#tracking) to capture paid invoices and then push to TaxJar using [v2/transactions/* ](https://developers.taxjar.com/api/reference/#transactions).

Please don't hesitate to reach out to support@taxjar.com if any specific questions come up around this.

**Comment by antwonlee** [comment]
Thanks @ScottRudiger  I think I got the gist after looking at the API documentation.  Since I only have nexus at Texas and my volume is low, the calculation shouldn't be too hard.  Do your API return responses to foreign transactions too?  As of what I can tell, it looks like TaxJar handles sales taxes only in USA, correct?

**Comment by ScottRudiger** [comment]
@antwonlee The API does support calculations for the United States, Canada, Australia, and the European Union. See [here](https://developers.taxjar.com/api/reference/#countries) for a list of all the countries supported and [here](https://support.taxjar.com/category/317-international) for additional tips.

**Comment by antwonlee** [comment]
``` ruby
order = client.tax_for_order({
  :from_country => 'US',
  :from_zip => '76006',
  :from_state => 'TX',
  :from_city => 'Fort Worth',
  :to_country => 'US',
  :to_zip => '76006',
  :to_state => 'TX',
  :to_city => 'Fort Worth',
  :amount => 4,
  :shipping => 0,
  :nexus_addresses => [
    {
      :id => 'Sicktastic',
      :country => 'US',
      :zip => '76006',
      :state => 'TX',
      :city => 'Fort Worth'
    }
  ],
  :line_items => [
    {
      :id => '1',
      :quantity => 1,
      :product_tax_code => '81162000A0000',
      :unit_price => 4,
      :discount => 0
    }
  ]
})
```

I have something like that ☝️ for getting the SaaS subscription tax, and it returns:

```
#<Taxjar::Tax order_total_amount: 4.0, shipping: 0.0, taxable_amount: 4.0, amount_to_collect: 0.33, rate: 0.0825, has_nexus: true, freight_taxable: true, tax_source: "origin", exemption_type: nil>
```

My nexus is in Texas and I sell SaaS subscription... 

A lot of from_ and to_ information were required.  Is this the shipping information?  Why do I need to include from_ and to_ when I don't have any shipping information? 

Am I supposed to put the client's info to `to_country`, `to_zip`, `to_state`, `to_city`, etc?

**Comment by ScottRudiger** [comment]
@antwonlee In the case of SaaS sales without a ship-to address, we generally recommend using the customer's billing address as a fallback.

**Comment by antwonlee** [comment]
Thanks @ScottRudiger 

I think I got a good understanding of how API should work now. 👍
