### ISSUE TITLE
Client doesn't throw Taxjar exceptions during outage

### ISSUE THREAD

**Issue by chigginsiii** [taxjar/taxjar-ruby#62]
Howdy!

This is happening during a major outage (1/11/21, 13:30-14:30 EST). Here's a log of the issue:

```
irb(main):014:0> Taxjar::Version.to_s
=> "2.6.1"
irb(main):015:0> c = ::Taxjar::Client.new(api_key: ENV['TAXJAR_API_KEY'])
irb(main):016:0> c.categories
=> []
irb(main):017:0> c.rates_for_location zipcode: 95060, city: 'Santa Cruz', state: 'CA', country: 'US'
Traceback (most recent call last):
        1: from (irb):17
NoMethodError (undefined method `each' for nil:NilClass)
irb(main):018:0>
```

I've traced it back to `model_attributes`, in this case it's a `set_attributes` call from trying to build a `Taxjar::Rate`, when I tried `tax_for_order` it was a `Taxjar::Tax`, so I don't think it's specific to the model.

(It would be swell if there was an option to get verbose http output for situations like these too.)

Thanks much!

**Comment by BenAkroyd** [comment]
Agreed, this caused a major issue with our store, blocking checkout, causing a significant loss of revenue. We have an emergency backup system in place for tax quoting in place should a taxjar outage occur (we understand it happens), however it failed to kick in as no Taxjar error was raised.
