### ISSUE TITLE
Taxjar::Client#show_order is supposed to return exemption_type but does not.

### ISSUE THREAD

**Issue by pdg137** [taxjar/taxjar-ruby#66]
[The documentation](https://developers.taxjar.com/api/reference/?ruby#get-show-an-order-transaction) for `show_order` shows that it should include an `exemption_type` parameter, but (as you can see from the example in the sidebar) this parameter is not actually included in the results.

Without that information, it seems like there's no way to check that an order was exempted correctly.

**Comment by fastdivision** [comment]
Hi @pdg137, are you seeing `exemption_type` returned from `show_order` directly from the Ruby API client? Just tested locally and I'm not seeing issues. This looks like an out-of-date API documentation example. We'll get it updated shortly.

**Comment by pdg137** [comment]
I was seeing what was in the documentation. However, after upgrading the gem to a more recent version, I am now seeing `exemption_type`, so I guess it is working!

The documentation is still out of date.
