### ISSUE TITLE
default User-Agent can cause 500 errors

### ISSUE THREAD

**Issue by hinkle-stripe** [taxjar/taxjar-ruby#72]
The default User-Agent set by this library can sometimes include characters that are not valid characters for an HTTP header.  When it does this, any requests made by the client result in a 500 response.

HTTP headers (of which User-Agent is one) [must](https://datatracker.ietf.org/doc/html/rfc5987) be encoded using the [ISO-8859-1 character set](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). Computer hostnames (at least on MacOS) permit characters that aren't part of the ISO-8859-1 character set, e.g. the curly apostrophe in "Jonathan Hinkle’s MacBook Pro".  Since this library puts the computer's hostname into the User-Agent string (via `uname -a`), that means that the User-Agent can end up containing characters that are not legal in ISO-8859-1. This scenario ends up causing some kind of conversion error on the server, resulting in a 500 for the client.

**Reproduction steps:**

1. set your computer's hostname to something that includes any character that isn't a part of ISO-8859-1 (e.g. curly apostrophe: `’`)
2. attempt to make a request using this library
3. response status code will be 500

**Potential fix:**

Update `Taxjar::Client#user_agent` to run its current return value through something like `.encode("ISO-8859-1", invalid: :replace, undef: :replace)`. This would result in a User-Agent string where the invalid bytes are replaced by "?", e.g. `"Jonathan Hinkle???s MacBook Pro"` for the hostname part.

It would be a good idea to confirm the behavior of characters that are not part of ASCII but are part of ISO-8859-1 (e.g. `å`) to confirm that they work without error.

**Comment by poops** [comment]
Thanks! This should be handled in v3.0.4
